class zabbix::client::install inherits zabbix {                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                               
  include ::zabbix::repo                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                               
  package { 'zabbix-agent':                                                                                                                                                                                                                                                    
    ensure      => present,                                                                                                                                                                                                                                                    
    require     => Yumrepo['zabbix'],                                                                                                                                                                                                                                          
  }                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                               
  file { '/etc/zabbix/zabbix_agentd.conf':                                                                                                                                                                                                                                     
    ensure      => file,                                                                                                                                                                                                                                                       
    content     => template('zabbix/zabbix_agentd.conf.erb'),                                                                                                                                                                                                                  
    mode        => '644',                                                                                                                                                                                                                                                      
    owner       => 'root',                                                                                                                                                                                                                                                     
    group       => 'root',                                                                                                                                                                                                                                                     
    require     => Package['zabbix-agent'],                                                                                                                                                                                                                                    
  }                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                               
}
